basePath: /
host: localhost:8000
info:
  contact:
    email: falecom@danielsilveira.dev.br
    name: Daniel Silveira
    url: http://danielsilveira.dev.br
  description: Prodct API Consulta CEP
  license:
    name: Daniel Silveira
    url: http://danielsilveira.dev.br
  termsOfService: http://swagger.io/terms/
  title: Consulta CEP Go Expert API multithreading
  version: "1.0"
paths: {}
swagger: "2.0"
